"""Add salary_structures table

Revision ID: 0c8b24c7241b
Revises: 6f009c0186c9
Create Date: 2026-08-22 10:22:05.895034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8b24c7241b'
down_revision: Union[str, Sequence[str], None] = '6f009c0186c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('wage_type', sa.String(length=50), nullable=False),
    sa.Column('defined_wage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('standard_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performance_bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_structures')
    # ### end Alembic commands ###
