"""add company_name column to employees table

Revision ID: 445c2031da92
Revises: e0d1a7b63f36
Create Date: 2026-08-22 15:47:38.614588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445c2031da92'
down_revision: Union[str, Sequence[str], None] = 'e0d1a7b63f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('company_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'company_name')
    # ### end Alembic commands ###
